--- # Ts is first playbook
- hosts: all
  user: ansadmin
  become: true
  connection: ssh
  gather_facts: no
  tasks:
    - name: Execute a command 
      command: bs -blt
      ignore_errors: yes
    - name: install httpd software
      yum: pkg=httpd state=installed
